# Generated by Django 2.1.1 on 2019-01-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favicon_finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favicon',
            name='fav_url',
            field=models.URLField(max_length=50),
        ),
        migrations.AlterField(
            model_name='favicon',
            name='url',
            field=models.URLField(max_length=50),
        ),
    ]
