# Generated by Django 2.1.1 on 2019-04-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favicon_finder', '0003_auto_20190404_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favicon',
            name='url',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
