# Generated by Django 2.1.1 on 2019-04-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favicon_finder', '0004_auto_20190408_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favicon',
            name='fav_url',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='favicon',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
